runtime: python39

entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

handlers:
  - url: /assets
    static_dir: assets

  - url: /chat
    script: auto

  - url: /.*
    script: auto

env_variables:
  DB_FILE: "diabetes_data.db"
  FAQ_FILE: "chatbot_dataset.txt"

automatic_scaling:
  min_instances: 0
  max_instances: 2
